using RealityCheck.Models;

namespace RealityCheck.Calibration;

// ============================================================================================
/// <summary>
/// Simple two-feature logistic regression scorer over isotropy and log-energy.
/// </summary>
public sealed class LogisticAiScorer
{
    private readonly double _w0;
    private readonly double _wIso;
    private readonly double _wLogEnergy;

    // ============================================================================================
    /// <summary>
    /// Initializes a new instance of the LogisticAiScorer class.
    /// </summary>
    /// <param name="bias">The bias term.</param>
    /// <param name="isoWeight">The weight for the isotropy feature.</param>
    /// <param name="logEnergyWeight">The weight for the log-energy feature.</param>
    public LogisticAiScorer(double bias, double isoWeight, double logEnergyWeight)
    {
        _w0 = bias;
        _wIso = isoWeight;
        _wLogEnergy = logEnergyWeight;
    }

    // ============================================================================================
    /// <summary>
    /// Predicts the probability that the given gradient features were generated by AI.
    /// </summary>
    /// <param name="f">The gradient features to predict.</param>
    /// <returns>The predicted probability.</returns>
    public double PredictProbability(GradientFeatures f)
    {
        var x1 = f.IsotropyRatio;
        var x2 = Math.Log(Math.Max(f.Energy, 1e-12));
        var z = _w0 + _wIso * x1 + _wLogEnergy * x2;
        return 1.0 / (1.0 + Math.Exp(-z));
    }

    // ============================================================================================
    /// <summary>
    /// Train a logistic model using batch gradient descent.
    /// </summary>
    /// <param name="samples">The samples to train on.</param>
    /// <param name="epochs">The number of epochs to train for.</param>
    /// <param name="learningRate">The learning rate.</param>
    /// <returns>The trained logistic ai scorer.</returns>
    public static LogisticAiScorer Train(
        IEnumerable<FeatureSample> samples, 
        int epochs = 4000, 
        double learningRate = 0.1)
    {
        var data = samples.ToList();

        if (data.Count == 0)
        {
            throw new ArgumentException("No samples provided", nameof(samples));
        }

        double w0 = 0, w1 = 0, w2 = 0;
        var n = data.Count;

        for (var epoch = 0; epoch < epochs; epoch++)
        {
            double g0 = 0, g1 = 0, g2 = 0;
            foreach (var s in data)
            {
                var x1 = s.Isotropy;
                var x2 = Math.Log(Math.Max(s.Energy, 1e-12));
                var z = w0 + w1 * x1 + w2 * x2;
                var p = 1.0 / (1.0 + Math.Exp(-z));
                var diff = p - (s.IsAi ? 1.0 : 0.0);
                g0 += diff;
                g1 += diff * x1;
                g2 += diff * x2;
            }

            var invN = 1.0 / n;
            w0 -= learningRate * g0 * invN;
            w1 -= learningRate * g1 * invN;
            w2 -= learningRate * g2 * invN;
        }

        return new LogisticAiScorer(w0, w1, w2);
    }
}

// ============================================================================================
/// <summary>
/// A sample of gradient features and whether it was generated by AI.
/// </summary>
public sealed record FeatureSample(
    double Isotropy, 
    double Energy, 
    bool IsAi, 
    string? Path = null);
