using RealityCheck.Models;

namespace RealityCheck.Calibration;

// ============================================================================================
/// <summary>
/// A calibrator for thresholding images based on their scores.
/// </summary>
public sealed class ThresholdCalibrator
{
    // ============================================================================================
    /// <summary>
    /// Finds a threshold that maximizes balanced accuracy (Youden's J) given labeled scores.
    /// </summary>
    public ThresholdCalibrationResult Calibrate(IEnumerable<CalibrationSample> samples)
    {
        var list = samples.ToList();
        if (list.Count == 0)
        {
            throw new ArgumentException("At least one sample is required.", nameof(samples));
        }

        var aiCount = list.Count(s => s.IsAi);
        var realCount = list.Count - aiCount;
        if (aiCount == 0 || realCount == 0)
        {
            throw new ArgumentException("Provide both AI and real samples for calibration.", nameof(samples));
        }

        var ordered = list.OrderBy(s => s.Score).ToList();

        double bestThreshold = ordered[0].Score;
        double bestJ = double.NegativeInfinity;
        double bestTpr = 0;
        double bestTnr = 0;

        foreach (var candidate in ordered.Select(s => s.Score))
        {
            var tpr = CountTruePositive(candidate, list) / (double)aiCount;
            var tnr = CountTrueNegative(candidate, list) / (double)realCount;
            var j = tpr + tnr - 1.0;

            if (j > bestJ)
            {
                bestJ = j;
                bestThreshold = candidate;
                bestTpr = tpr;
                bestTnr = tnr;
            }
        }

        return new ThresholdCalibrationResult(bestThreshold, bestTpr, bestTnr, (bestTpr + bestTnr) / 2.0);
    }

    // ============================================================================================
    /// <summary>
    /// Scores a list of images and returns a list of calibration samples.
    /// </summary>
    /// <param name="labeledImages">The list of images to score.</param>
    /// <param name="detector">The detector to use.</param>
    /// <returns>The list of calibration samples.</returns>
    public IEnumerable<CalibrationSample> ScoreImages(IEnumerable<(string Path, bool IsAi)> labeledImages, AiDetector detector)
    {
        foreach (var (path, isAi) in labeledImages)
        {
            var result = detector.Detect(path);
            yield return new CalibrationSample(result.Score, isAi, path);
        }
    }

    // ============================================================================================
    /// <summary>
    /// Counts the number of true positives.
    /// </summary>
    /// <param name="threshold">The threshold to use.</param>
    /// <param name="samples">The list of samples to count.</param>
    /// <returns>The number of true positives.</returns>
    private static int CountTruePositive(double threshold, IReadOnlyCollection<CalibrationSample> samples) =>
        samples.Count(s => s.IsAi && s.Score >= threshold);

    // ============================================================================================
    /// <summary>
    /// Counts the number of true negatives.
    /// </summary>
    /// <param name="threshold">The threshold to use.</param>
    /// <param name="samples">The list of samples to count.</param>
    /// <returns>The number of true negatives.</returns>
    private static int CountTrueNegative(double threshold, IReadOnlyCollection<CalibrationSample> samples) =>
        samples.Count(s => !s.IsAi && s.Score < threshold);
}

// ============================================================================================
/// <summary>
/// A sample of a scored image and whether it was generated by AI.
/// </summary>
public sealed record CalibrationSample(double Score, bool IsAi, string? Path = null);

// ============================================================================================
/// <summary>
/// The result of a threshold calibration.
/// </summary>
public sealed record ThresholdCalibrationResult(double Threshold, double TruePositiveRate, double TrueNegativeRate, double BalancedAccuracy);
